name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    tags:
    
concurrency: ci-${{ github.ref }}

  #schedule:
    # * is a special character in YAML so you have to quote this string
   # - cron:  '0 */6 * * *'
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_GHCR: ghcr.io/${{ github.repository }}
  IMAGE_NAME_DOCKER: austinsonger/elastic-detection-clivv

permissions:
  contents: read
  packages: write



jobs:

  build_release:
    name: Build and Release
    runs-on: ubuntu-latest

    outputs:
      labels: ${{ steps.meta.outputs.labels }}
      tags: ${{ steps.meta.outputs.tags }}


    steps:
    - uses: actions/checkout@v2
    
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
          
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build the Docker image
      run: docker build . --file elastic-detection/Dockerfile --tag elastic-detection-cli:$(date +%Y%m%d)
  
    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true      
